#!/usr/bin/php
<?php
   if($argc==4 && $argv[1]=='--generate' && $argv[2] !=''){
      // echo "Creating new {$argv[2]} action....\n";

      $classname=ucwords(strtolower($argv[2]));
      $objectname=strtolower($argv[2]);
      $inputFile=strtolower($argv[3]);
      // Controller
      $activity_name=$classname."Activity.php";
     echo "
    public function uploadAction(Request \$request)
    {
        \${$objectname}=new {$classname}();
        \${$objectname}->file=\$request->file['{$inputFile}'];
        \$response=\${$objectname}->upload(\"path\");
        if(\$response->success){
            \$request->input[\"filename\"]=\$response->filename;
            //to store or update  call the method 
            \$this->store(\$request); OR \$this->update(\$request);
        }
       // echo json_encode(\$response);
    }
    
    ";
  } 
?>